#!/bin/bash

yum install -y libffi libffi-devel zlib-devel
yum remove -y cmake

python -m pip install pip --upgrade
python -m pip install cmake

curl https://raw.githubusercontent.com/limix/chi2comb/master/install --output install-chi2comb
bash install-chi2comb
